pipeline:
  docker:
      image: plugins/docker
      repo: lowet84/pwa-template
      secrets: [ docker_username, docker_password ]
      tags: latest
      when:
        branch: master

  deploy:
    image: appleboy/drone-ssh
    host: home.local
    username: root
    secrets: [ ssh_key ]
    port: 22
    script:
      - cd homeserver2/wip/pwa-template
      - upgrade-compose

